name: Vprofile actions
on: workflow_dispatch
env:
  ECR_REPOSITORY: vprofileapp
  AWS_DEFAULT_REGION: us-east-1
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Maven test
      run: mvn test

    - name: Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Setup java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurun'
        java-version: '11'

  Build_and_Publish:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
    - name: upload image to ECR
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        registry: ${{ secrets.REGISTRY }}
        repo: ${{ env.ECR_REPOSITORY }}
        region: ${{ env.AWS_DEFAULT_REGION }}
        auto_tag: true
        daemon_off: false
        dockerfile: ./Dockerfile
        context: ./